version: '2'


networks:
    bibbox-default-network:
      external: true

services:
    §§INSTANCE-dev-app-checker:
        image: bibbox/app-checker
        container_name: §§INSTANCE-dev-app-checker
        depends_on:
            - §§INSTANCE-dev-app-checker-redis
        restart: unless-stopped
        networks:
            - bibbox-default-network
        ports:
            - '§§PORT:5000'

    §§INSTANCE-dev-app-checker-redis:
        image: 'redis:3.0.7'
        command: redis-server --requirepass bibbox4ever
        container_name: §§INSTANCE-dev-app-checker-redis
        restart: unless-stopped
        networks:
            - bibbox-default-network
        ports:
            - '6388:6379'